// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etxysagzkvaormcvvmns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0eHlzYWd6a3Zhb3JtY3Z2bW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTQ3MzcsImV4cCI6MjA3MTE3MDczN30.M03DfOHXQgKX7hbFmcHjhj5ho8KJCMAox09ITF1O54w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});